# Generated by Django 6.0.3 on 2026-03-11 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='allowed_departments',
        ),
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='departments.department'),
            preserve_default=False,
        ),
    ]
